### ISSUE TITLE
coveralls coverage monitoring

### ISSUE THREAD

**Issue by alawatthe** [jscs-dev/jscs-jsdoc#102]
It would be really great to have it.

And according to https://github.com/jscs-dev/jscs-jsdoc/issues/15#issuecomment-65008674 it is the only thing left to before 1.0.0 can be released ;-D

**Comment by zxqfox** [comment]
@alawatthe Thanks, done ;-)

**Comment by alawatthe** [comment]
That was quick. Awesome :+1:
