### ISSUE TITLE
New Rule: Require Description to be a complete sentence.

### ISSUE THREAD

**Issue by dtracers** [jscs-dev/jscs-jsdoc#106]
This is something that checkstyle has in java and I think I might implement this rule.

Where a complete sentence one that must start with a capitol letter and end end with a period.
This can also be added with the description requires a new line and we can say that the first sentence must have a separate line from the other sentences (even if both sentences are on the same line)

Basically an example is
```
/**
 * This is a valid description.
 */
function foo() {
}

/**
 * this is invalid.
 */
function bar() {
}

/**
 * This is also invalid
 */
function foobar() {
}
```

The extra combined rule with the newline and the complete sentence are both true.

```
/**
 * This is the first sentence. This second sentence must be on a new line
 */
function func() {
}
```

**Comment by zxqfox** [comment]
Sounds good!

**Comment by dtracers** [comment]
How do you feel about the combined rule of the new line and the sentence?

Or do you think that should be in the description must be a single complete sentence on one line by default?

**Comment by dtracers** [comment]
Actually I am going to make a new rule for this.

**Comment by dtracers** [comment]
associated pull request #109

**Comment by zxqfox** [comment]
> Actually I am going to make a new rule for this.

:tada:  Agreed!

> Associated pull request #109

I've left few notes there, some of them can be discussed, looks good at all!

**Comment by zxqfox** [comment]
Thanks again, landed at master, will publish this asap! :palm_tree:

**Comment by dtracers** [comment]
Awesome Thanks!

I will probably be making some new rules tonight as well.
