### ISSUE TITLE
Error "Missing access tag for ..." for overriden method

### ISSUE THREAD

**Issue by dfilatov** [jscs-dev/jscs-jsdoc#114]
I have the following code:
```js
/** @override */
_myMethod : function() {
    ...
}
```
I get an error "Missing access tag for myMethod" while I'm trying to process the code with jscs-jsdoc.
I don't want to copy and paste all the tags from base method because it's redundant at all.

**Comment by zxqfox** [comment]
@dfilatov I see would be nice to skip checking for redundancy if there is `@override` tag. Is it ok for ya?

**Comment by dfilatov** [comment]
It would be perfect.

**Comment by zxqfox** [comment]
@dfilatov Thanks!

Landed and published in v1.1.0
