### ISSUE TITLE
checkAnnotations: Preset names should be case-insensitive

### ISSUE THREAD

**Issue by markelog** [jscs-dev/jscs-jsdoc#117]
As a suggestion, in docs for `checkAnnotations` rule it says - 
> There are 3 presets for Closure Compiler, JSDoc3 and JSDuck5.

But for `JSDoc3` it shows the unsupported preset errror

**Comment by zxqfox** [comment]
Yes, but there is "for". And below there are correct values for them. Is it confusing?
