### ISSUE TITLE
Implement requireReturnDescription

### ISSUE THREAD

**Issue by weekens** [jscs-dev/jscs-jsdoc#122]
Similar to `requireParamDescription`, but for returns.

I'd like the following JSDoc to be invalid:

    /**
     * Some description.
     *
     * @returns {Boolean}
     */
    foo: function() {
      return false;
    }

**Comment by zxqfox** [comment]
@weekens Thanks for suggestion. Do you mind to tackle this? ;-)

It's easy as: https://github.com/jscs-dev/jscs-jsdoc/blob/master/lib/rules/validate-jsdoc/require-param-description.js

What to do:
- add rule file (like require-param-description but with another tags)
- add specs
- update readme

**Comment by weekens** [comment]
@zxqfox, I'll try to!

**Comment by weekens** [comment]
Created a pull request: https://github.com/jscs-dev/jscs-jsdoc/pull/125
