### ISSUE TITLE
Sentences with trailing ). and ". (and similar) are marked invalid by requireDescriptionCompleteSentence rule

### ISSUE THREAD

**Issue by weekens** [jscs-dev/jscs-jsdoc#123]
The sentences like:

    Handles user input (click or keypress).

should be considered valid by `requireDescriptionCompleteSentence`.

For now the rule yields `Sentence must end with a period.` message.

**Comment by zxqfox** [comment]
Regex failing, yup. Thanks for a report.

https://github.com/jscs-dev/jscs-jsdoc/blob/master/lib/rules/validate-jsdoc/require-description-complete-sentence.js#L35

**Comment by wooorm** [comment]
Just had the same when a tick was used before a period: ``Detach `$node`.`` It’s the `\w` on https://github.com/jscs-dev/jscs-jsdoc/blob/master/lib/rules/validate-jsdoc/require-description-complete-sentence.js#L35 which should probably be something else. `\S` maybe?

**Comment by zxqfox** [comment]
Definitely! ;-) Wanna tackle this?

**Comment by wooorm** [comment]
Will do
