### ISSUE TITLE
requireDescriptionCompleteSentence: Failure on multiple paragraphs in description without dot

### ISSUE THREAD

**Issue by wooorm** [jscs-dev/jscs-jsdoc#129]
See [wooorm/jscs-jsdoc-bug](https://github.com/wooorm/jscs-jsdoc-bug/blob/master/index.js) for a not-working example. It’s on jscs 2.0.

Also: it seems to need all the lines in the jscdoc comment to fail.

**Comment by zxqfox** [comment]
After your fix it works fine but wants a period at the end of list.

**Comment by zxqfox** [comment]
```
Sentence must end with a period. at qwe.js :
     5 | * Baz:
     6 | *
     7 | * - Qux
--------^
     8 | * @param {string} x
     9 | */
```

**Comment by wooorm** [comment]
Hmm. At least there’s no failure anymore. However, it keeps complaining about non-existing problems:

First: `index.js: line 7, col 0, Sentence must end with a period.` (it actually means `line 5, col 3`, at `Baz:`, because when I add a dot after `Qux` the message stays),

If I fix that, I get `index.js: line 5, col 3, You started a new line with an upper case letter but previous line does not end with a period.` (which is false, and related to this rule not detecting the tick-period at 3:8-3:10).

Although this is a pretty weird example!

**Comment by zxqfox** [comment]
;-( Guess we need to rethink this rule.
