### ISSUE TITLE
Rule "jsDoc" is already registered

### ISSUE THREAD

**Issue by christianv** [jscs-dev/jscs-jsdoc#131]
Using `jscs` version `2.0.0`.

1. Set `.jscsrc` to:

    ```json
    {
      "plugins": [
        "jscs-jsdoc"
      ]
    }
    ```
2. Run `jscs .` in the command line.

You immediately get the following response: `Rule "jsDoc" is already registered`

**Comment by christianv** [comment]
Also see #128

**Comment by christianv** [comment]
@zxqfox any proposal on how we might be able to fix this? Currently we need to use an older version of `jscs` to make `jsDoc` linting work.

**Comment by zxqfox** [comment]
For now you can move `"plugins": ["jscs-jsdoc"]` out of your `.jscsrc` to use bundled version of this plugin.

I'm still not sure how to resolve this issue to allow users install custom version of `jsdoc` plugin. Need some time to decide (or some contribution of a good guy ;-).

**Comment by markelog** [comment]
Honestly, don't see the problem there, we already have installed `jscs-jsdoc` plugin, so you don't need to put it in `plugins`

**Comment by szarouski** [comment]
@zxqfox I'm a good guy :) Let me know what you think is the best. My suggesting - lets remove jscs-jsdoc from jscs dependencies and finish https://github.com/jscs-dev/jscs-jsdoc/issues/128?

**Comment by zxqfox** [comment]
Closing this for now as resolved. If somebody still xp'd this issue — please let me know.
