### ISSUE TITLE
requireParamTypes and argument with properties

### ISSUE THREAD

**Issue by markelog** [jscs-dev/jscs-jsdoc#132]
From https://code.google.com/p/jsdoc-toolkit/wiki/TagParam

```js
/**
  * @param userInfo Information about the user.
  * @param userInfo.name The name of the user.
  * @param userInfo.email The email of the user.
  */
```
But jsDoc will warn for such definitions

**Comment by zxqfox** [comment]
@markelog I don't see it's broken ;-( Need more info. See #133

**Comment by markelog** [comment]
Did you run `checkParamNames` on code:
```js
 /**
  * @param userInfo Information about the user.
  * @param userInfo.name The name of the user.
  * @param userInfo.email The email of the user.
  */
 function logIn(userInfo) {
        doLogIn(userInfo.name, userInfo.email);
 }
```

?

**Comment by zxqfox** [comment]
I've updated test, still no error ;-(

https://github.com/jscs-dev/jscs-jsdoc/pull/133/files#diff-4170383ccbd6bc30dfa2c057c8393ce9R484

**Comment by markelog** [comment]
Sorry, it seems `requireParamTypes` is offending rule

**Comment by zxqfox** [comment]
Hm, does requireParamTypes not works as expected? What you suggest to do? ;-)

**Comment by markelog** [comment]
No, i'm just stupid!

**Comment by zxqfox** [comment]
;-( okay.
