### ISSUE TITLE
Parameter type validation for JSDuck should allow primitives types

### ISSUE THREAD

**Issue by jdforrester** [jscs-dev/jscs-jsdoc#137]
Per the [JSDuck documentation](https://github.com/senchalabs/jsduck/wiki/Type-Definitions#type-names), values can be objects or primitive values. It's useful to distinguish whether you're expecting an object or a primitive. However, the latter case does not work.

### Primitives types which fail
* `{boolean}`
* `{number}`
* `{string}`

### Equivalent objects which work
* `{Boolean}`
* `{Number}`
* `{String}`

**Comment by Krinkle** [comment]
:+1:

**Comment by zxqfox** [comment]
Guys, both of them should works, just choose what you need. http://jscs.info/rule/jsDoc.html#checktypes

If you want to use both of them in the same project — seems like we need new rule value.

**Comment by Krinkle** [comment]
I think `checkType: "strictNativeCase"` will do what we want. We don't actually use boxed primitives. Allowing both only causes confusion and wasted human efforts to fix them to be lowercased instead. This rule would allow us to enforce that.

**Comment by jdforrester** [comment]
Sorry, this can be marked as resolved.
