### ISSUE TITLE
Enforce existance, but only for functions that has arguments

### ISSUE THREAD

**Issue by szarouski** [jscs-dev/jscs-jsdoc#139]
In my opinion only hacky/unclear code needs description otherwise developers should express what code is doing using code, not comments. Following that logic and taking in count cases that some functions might not have any arguments is it possible to enforce jsdoc existance, but only for functions which take arguments? Otherwise I need to put empty comments at the top of each function. Thank you.

**Comment by zxqfox** [comment]
Yeah, why not? Thanks for contribution. Just need to decide how to do it.

**Comment by szarouski** [comment]
Hi @zxqfox I'll try to figure it out. If there are any examples which might help me along the way, please let me know.

**Comment by zxqfox** [comment]
We usually doing it with exceptions like `allExcept: ['some', 'thing', 'etc']`.

For now there are 3 options: anonymous, exports, expressions. Feels like we need another one for your case. Any ideas how to call it? Something like `paramless`?

https://github.com/jscs-dev/jscs-jsdoc/blob/master/lib/rules/validate-jsdoc/enforce-existence.js#L15-L20

**Comment by szarouski** [comment]
`paramless` sounds pretty cool :+1: Less cool, and a little boring alternatives are `no-arguments`, `no-parameters`, `no-params`, `without-params`. It will read like `enforceExistence` for `allExcept: ['without-params']`. I'm fine with any of those including `paramless`, so it is up to you :)
