### ISSUE TITLE
requireDescriptionCompleteSentence: dot in abbreviation is treated like a sentence end

### ISSUE THREAD

**Issue by tonyganch** [jscs-dev/jscs-jsdoc#145]
With this line in config:
```
requireDescriptionCompleteSentence: true
```
dots in abbreviations (like `e.g.` or `i.e.`) are mistakenly treated like sentence end.
For example, this line throws an error demanding `e.g.` to be `e.G.`:
```js
/**
 * Checks if token is part of an @-word (e.g. `@import`, `@include`).
 */
```
Maybe "sentence end" should be "dot + space" instead of just "dot"?

**Comment by zxqfox** [comment]
Thanks for reporting.

Related to #129
