### ISSUE TITLE
requireDescriptionCompleteSentence: Doesn't recognize sentence ending with parenthesis

### ISSUE THREAD

**Issue by marian-r** [jscs-dev/jscs-jsdoc#157]
Doesn't recognize valid sentence with parentheses at the end before the dot. It seems as it fails with any non word character.

```
28 | * Checks for false positives (null) and false negatives (functions).
------------------------------------------------------------------------^
```

**Comment by zxqfox** [comment]
Thanks for report. Please, try v1.2.0, it should be fixed already.

**Comment by marian-r** [comment]
Yes, it's fixed. Thanks! I tried it as a standalone plugin, but when can I expect jscs itself to load the new version of this jsDoc rule?

**Comment by zxqfox** [comment]
@marian-r We planning to ship it in few days or weeks. Thanks! ;-)

**Comment by marian-r** [comment]
Great :+1:
