### ISSUE TITLE
What was the reason for removing a period after the error message?

### ISSUE THREAD

**Issue by gajus** [jscs-dev/jscs-jsdoc#166]
https://github.com/jscs-dev/jscs-jsdoc/commit/c7684978337ff8679296923e0f971addec376e9e#diff-b42988fd48ef517b52861127d96304b8L80

In this commit you have removed a period after all the error messages. What is the reason for that?

**Comment by zxqfox** [comment]
In JSCS for some reason we don't have periods in error messages.

E.g.:
- https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/disallow-arrow-functions.js#L64
- https://github.com/jscs-dev/node-jscs/search?utf8=%E2%9C%93&q=errors.add

**Comment by gajus** [comment]
It is somewhat ironic that an error for a rule `requireDescriptionCompleteSentence` is without a closing period. But if thats the convention, thats the convention.

**Comment by zxqfox** [comment]
@gajus up ↑ ;-)
