### ISSUE TITLE
enforceExistence rule not work properly for anonymous function. 

### ISSUE THREAD

**Issue by annsk** [jscs-dev/jscs-jsdoc#189]
For function in this code jscs throw error. It should be param for suppress it.

```
var modalInstance = $modal.open({
         templateUrl: 'modalColor.html',
         controller: 'ModalColorCtrl as mColor',
         resolve   : {
                colors: function() {
                        return 1;
                }
         }
});
```

**Comment by zxqfox** [comment]
What the config you have?

Did you tried `"enforceExistence": {"allExcept": ["expressions", "paramless-procedures"]}`?

See also: http://jscs.info/rule/jsDoc#enforceexistence

**Comment by annsk** [comment]
Ok, it works. I'd old version. But now I have next problem.

In my config I has:
```
"disallowSpaceAfterObjectKeys": { "allExcept": ["aligned", "singleline"] },
"requireAlignedObjectValues": "all",
```
But here: 
```
White: {
      outer: 'NONE',
      inner: 'NONE',
      core : 'WHITE'
}
```
I got an error: Illegal space after key (in line with key "core").

**Comment by zxqfox** [comment]
Thanks for report.

Yeah, that's a known bug: https://github.com/jscs-dev/node-jscs/issues/2080, but it doesn't belongs to jscs-jsdoc.

If you have any other question, feel free to ask ;-)
