### ISSUE TITLE
Checking that if method is @private or @protected then it should have trailing underscore

### ISSUE THREAD

**Issue by qfox** [jscs-dev/jscs-jsdoc#5]
According to mdevils/node-jscs#210

**Comment by tonyganch** [comment]
> Do we really need to check methods with trailing underscores? Or just leading?

I would love to get `trailingUnderscoreAccess` option, since we write private methods `likeThis_`. Can you consider implementing this feature, please?

**Comment by zxqfox** [comment]
@tonyganch Please, file an issue ;-)
