### ISSUE TITLE
"unavailable tag return"

### ISSUE THREAD

**Issue by necolas** [jscs-dev/jscs-jsdoc#82]
Since updating to `0.3.x`, I get a lot of linting errors where there previously were none.

Config:

```js
  jsDoc: {
    checkAnnotations: 'closurecompiler',
    checkParamNames: true,
    checkRedundantParams: true,
    checkRedundantReturns: true,
    requireParamTypes: true,
    requireReturnTypes: true
  }
```

Example that produces the error:

```js
/**
 * Pad the given string so that it is at least `len` length.
 * @param  {String} str
 * @param  {Number} len
 * @return {String}
 */
function padUntil(str, len) {
  return str + Array(len - str.length).join(' ');
}
```

It's not clear to me what the problem is now.

**Comment by zxqfox** [comment]
Thanks for reporting.

I think that's because `closurecompiler` set was updated (that's a reason why minor version was bumped). Did you looked at #76?

Anyway, 0.4 branch have `@return` in preset and should works fine.
Is it possible for you to upgrade to the latest version?

**Comment by necolas** [comment]
Oh, didn't notice 0.4.x. Upgraded and that removed the issues with `return` but there are others I'm noticing now:

```
unavailable tag file
unavailable tag overview
unavailable tag fileoverview
unexpected data in tag private
```

The `file`/`overview`/`fileoverview` tag is defined as JSDoc:
http://usejsdoc.org/tags-file.html

The private tag apparently accepts a type value for closure, but the closure recommendation is to use `type` separately now:

http://usejsdoc.org/tags-private.html
https://developers.google.com/closure/compiler/docs/js-for-compiler

I also get another error – `redundant returns statement` – on functions like this:

```js
/**
 * Gets the ListenableKey for the event or null if no such
 * listener is in use.
 *
 * @param {string|!EventId<EVENTOBJ>} type The name of the event
 *     without the 'on' prefix.
 * @param {function(this:SCOPE, EVENTOBJ):(boolean|undefined)} listener The
 *     listener function to get.
 * @param {boolean} useCapture Whether the listener is a capturing listener.
 * @param {SCOPE=} listenerScope Object in whose scope to call the
 *     listener.
 * @return {./listenable.ListenableKey} the found listener or null if not found.
 * @template SCOPE,EVENTOBJ
 */
EventTarget.prototype.getListener = function (type,
  listener, useCapture, listenerScope) {
  return this.eventTargetListeners.getListener(String(type), listener,
                                               useCapture, listenerScope);
};
```

**Comment by zxqfox** [comment]
Are these tags (`file`, `overview`, `fileoverview`) should be a part of `closurecompiler` set?

I'm fixing the rest.

**Comment by zxqfox** [comment]
Also about `{./listenable.ListenableKey}` you should take a look at https://github.com/Kuniwak/jsdoctypeparser/issues/6 — we based on `jsdoctypeparser` and this type-string is unparsable (read "invalid").

Still investigating why this rule failing on invalid types.

**Comment by zxqfox** [comment]
What you think about `@private {type}` notation? Current docs (as you said) recommend to use separate `@type` tag.
Also you can shut up `jscs-jsdoc` with `checkAnnotations`: { extra: { private: true } }` so it's not a problem for custom or old jsdoc-comments.

I think we should left preset as is (as closest to the current `cc` set). Thoughts?

**Comment by zxqfox** [comment]
Patch for `checkRedundantReturns` landed in v0.4.4. Thanks!

**Comment by necolas** [comment]
Thanks!

Yeah I switched all the `@private` to use `@type` when needed, especially since it is what cc recommends now. Don't think you need to deal with that. However, the `@file(overview)` tags are part of JSDoc apparently. I've been using the `extra` object for cc-specific tags like `@preserveTry` and `@suppress`.

**Comment by zxqfox** [comment]
Can we open an separate issue about `@file(overview)` tags? Or if you sure that it's a part of **any** jsdoc dialect — I can just add it (or send PR ;-).

**Comment by necolas** [comment]
Done #83. Thanks
