### ISSUE TITLE
Add support for file / overview / fileoverview tag in closurecompiler

### ISSUE THREAD

**Issue by necolas** [jscs-dev/jscs-jsdoc#83]
As defined in JSDoc:

http://usejsdoc.org/tags-file.html

**Comment by zxqfox** [comment]
@necolas Thanks for filing it.

For now `closurecompiler` set is merge of https://developers.google.com/closure/compiler/docs/js-for-compiler#tags and
https://code.google.com/p/jsdoc-toolkit/wiki/TagReference

On the second page we have `@fileOverview` tag — that's what you need I think.
And it's in set https://github.com/jscs-dev/jscs-jsdoc/blob/master/lib/tags/closurecompiler.json#L22 — Not the case for jsdoc-toolkit and jsdoc3 are different ([jsdoc3 tag set](https://github.com/jscs-dev/jscs-jsdoc/blob/master/lib/tags/jsdoc3.json#L31)).

I'm still not sure for now that we should add aliases for `@fileOverview` there.

**Comment by necolas** [comment]
OK, we'll switch to `@fileOverview` assuming closurecompiler is cool with it. Thanks

**Comment by zxqfox** [comment]
If you using some tool to autogen docs with cc — please try to use other aliases there. It would be very helpful.

**Comment by zxqfox** [comment]
@necolas I feel like a bad guy who forced you to use old tag. According to https://code.google.com/p/jsdoc-toolkit/: "...project is no longer..." and it redirects to github account of jsdoc3. So you're right, and I'm wrong. Sorry for that.

Also I'm thinking that better to have sets for different docgen tools like `jsdoc3`, `doxx` or `yuidoc` (if somebody need it). Separated `closurecompiler` set probably is a good thing, but better to have it inside `jsdoc3` (at least extend `cc` set with `jsdoc3`).

Am I right?

**Comment by necolas** [comment]
I don't know about how much closurecompiler and jsdoc3 are related, but your plan sounds ok to me. Hard to find a list of all the supported closurecompiler tags. For example, various google projects have `@suppress` and `@preserveTry`, but they aren't documented in the contemporary closure docs. Easy to add to the `extra` too.

Thanks for your help with this.
