### ISSUE TITLE
AssertionError with "requireParamTypes": true

### ISSUE THREAD

**Issue by tersmitten** [jscs-dev/jscs-jsdoc#86]
```js
AssertionError: Unable to add an error, `column` should be a positive number but -1 given
    at Object.Errors.add (/usr/lib/node_modules/jscs/lib/errors.js:43:9)
    at addError (/usr/lib/node_modules/jscs-jsdoc/lib/rules/validate-jsdoc.js:155:28)
    at /usr/lib/node_modules/jscs-jsdoc/lib/rules/validate-jsdoc.js:169:25
    at Object.validateParamTag (/usr/lib/node_modules/jscs-jsdoc/lib/rules/validate-jsdoc/require-param-types.js:17:16)
    at /usr/lib/node_modules/jscs-jsdoc/lib/rules/validate-jsdoc.js:135:27
    at Array.forEach (native)
    at DocComment.<anonymous> (/usr/lib/node_modules/jscs-jsdoc/lib/rules/validate-jsdoc.js:134:46)
    at Array.forEach (native)
    at DocComment.forEachTag [as iterate] (/usr/lib/node_modules/jscs-jsdoc/lib/jsdoc.js:65:19)
    at /usr/lib/node_modules/jscs-jsdoc/lib/rules/validate-jsdoc.js:128:28
```

Our `.jscsrc` looks like this:

```js
{
	"preset": "yandex",
	"validateIndentation": "\t",
	"disallowQuotedKeysInObjects": "allButReserved",
	"requireCapitalizedConstructors": true,
	"safeContextKeyword": ["that"],

	"excludeFiles": [
		"**/node_modules/**"
	],
	"plugins": [
		"jscs-jsdoc"
	],
	"jsDoc": {
		"checkAnnotations": "jsdoc3",
		"checkParamNames": true,
		"checkRedundantParams": true,
		"checkReturnTypes": true,
		"checkRedundantReturns": true,
		"checkTypes": "strictNativeCase",
		"checkRedundantAccess": "enforceLeadingUnderscore",
		"leadingUnderscoreAccess": true,
		"enforceExistence": "exceptExports"
	}
}
```

**Comment by zxqfox** [comment]
Would be great also to see some code. Please ;-)

**Comment by zxqfox** [comment]
I'm not sure that I've fixed this but I can't repeat it. Please provide some test code to be sure or test on your case by self with the latest master.

Thanks for contribution!

**Comment by dtracers** [comment]
We found that it can be in the case was
* @param paramName
*            {ParamType}

When we removed the jsdoc plugin we were notified that this was the error (from normal jscs) and when we fixed it then the plugin worked when we added it back.

**Comment by zxqfox** [comment]
@dtracers Wow. Please provide version of jscs and jscs-jsdoc. I want to repeat it by self (bug should be fixed, especially if it randomly affects jscs plugins).

**Comment by dtracers** [comment]
Jscd-jsdoc "=0.4.5" (but happened on 0.4.6 too)
Grunt-Jscs 1.5.0 and 1.6.0
I did not try other versions.

When we did remove jsdocs it said that the param type did not exist.
Because we had it after the name of the param.

**Comment by zxqfox** [comment]
@dtracers Yeah, It doesn't supported atm. Any reason to write type after variable name?

**Comment by dtracers** [comment]
I find it is easier to separate the variable name from the message.  But we
have been putting the message on the next line so we don't need it after
anymore.

**Comment by zxqfox** [comment]
@dtracers Good news! Thanks for response ;-)
