### ISSUE TITLE
add option to enforceExistence only on module.exports ? 

### ISSUE THREAD

**Issue by TripledT** [jscs-dev/jscs-jsdoc#87]
The enforceExistence option supports all and exceptExports.  I was wondering what the reason was for excluding exports from the check ?  It seems that since exports is what is being shared, that they should be documented.

**Comment by zxqfox** [comment]
In some cases no need to have jsdoc for files like:
```
module.exports = function () {
  return {
    data: 'data',
    more: 'foobar',
    plurals: (n) => n%10 === 1 && (n%100 < 10 || n%100 > 20);
  };
};
```

And files like that don't need documentation for `.exports`.

Anyway, if you feel that you need to describe each function in your code — use `true` ;-).

**Comment by zxqfox** [comment]
I'm closing this for now, feel free to discuss if you think that it should be reworked.
