### ISSUE TITLE
Both usage of `abstract` and `returns` properties

### ISSUE THREAD

**Issue by tenorok** [jscs-dev/jscs-jsdoc#93]
Hello!
I want to declare interface of abstract function, but I have a problem with both usage of `abstract` and `returns` properties.
```js
Redundant return statement at ./code.js :
   476 |     * @abstract
   477 |     * @returns {Number}
---------------^
   478 |     */
   479 |    getPopupWidth: function() {},
```

It is bug?

**Comment by zxqfox** [comment]
@tenorok It is unexpected behaviour. ;-)

Feels like we need to skip checking this for `@abstract` declarations.

**Comment by tenorok** [comment]
Cool! :star2:
